print('hello,world!!!')
nome = input('Qual o seu nome?')
sobrenome = input('Qual seu sobrenome?')
idade = int(input('Qual a sua idade?'))
ano_De_Nascimento = int(2021 - idade)
print('Olá ' , nome, '...')
print('Seu sobrenome é ', sobrenome,'...')
print('Você tem ' , idade, ' anos...')
print('E você nasceu no ano de ',ano_De_Nascimento ,'...')
print('Foi um prazer falar com você!!!')
